### ISSUE TITLE
Can't update spreadsheet

### ISSUE THREAD

**Issue by briandaviddavidson** [biovisualize/d3visualization#9]
I tried to add a project to the list, but the spreadsheet was locked to read only

**Comment by edriessen** [comment]
I have the same issue.

**Comment by stared** [comment]
I needed to ask for permission to edit it (somewhere from Google Docs menu).

**Comment by briandaviddavidson** [comment]
@stared is correct. If you go to the spreadsheet, you can request access to edit it from the owner.
